name: Build

on: [push, pull_request]
 
jobs:
  tests:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install lua
        run: apt install lua5.1
      - name: Run Unit Tests
        run: "bash ./runUnitTests.sh"